### ISSUE TITLE
"SSL certificate problem"

### ISSUE THREAD

**Issue by fiskhandlarn** [Jamalc0m/wphunter#1]
When trying on different sites (all with WordPress, but only some of them using SSL) I get this message before the script quits:

```
SSL certificate problem: unable to get local issuer certificate
```

I'm running the script in cygwin on Windows 10 with PHP 7.1.9 (cli).

**Comment by fiskhandlarn** [comment]
I think I found the issue in the code, gonna send a PR soon!

**Comment by fiskhandlarn** [comment]
https://github.com/Jamalc0m/wphunter/pull/2

**Comment by Jakson2030** [comment]
Thank you  .. I have pulled your request :)
