### ISSUE TITLE
Getting WordPress version for sites without readme.html

### ISSUE THREAD

**Issue by fiskhandlarn** [Jamalc0m/wphunter#3]
Not all sites have the /readme.html uploaded/accessible. Would it be possible to scrape the html for the generator meta tag instead or as a backup?
```
<meta name="generator" content="WordPress 4.4.2" />
```

**Comment by fiskhandlarn** [comment]
Also, `readme.html` no longer contains the WordPress version: https://github.com/WordPress/WordPress/blob/master/readme.html

**Comment by Jakson2030** [comment]
There are many websites that have old version such as 3,6 , 3,7  or even older etc .. which have readme.html contains the WordPress version, and they don't have the meta generator tag in the page.
If you see the script it uses different ways to get the version including : readme.html, meta tag, RSS feed,/wp-links-opml, feed atom etc...

**Comment by Jakson2030** [comment]
Thanks for your contribution :)

**Comment by fiskhandlarn** [comment]
@Jamalc0m Oh I see, thanks for the clarification!
