### ISSUE TITLE
Move wphunter.co api to this script instead

### ISSUE THREAD

**Issue by fiskhandlarn** [Jamalc0m/wphunter#4]
Any chance you can move the functionality from https://www.wphunter.co/api/list.php into this script instead? It doesn't feel quite right to trust something we can't really see the source for.

**Comment by fiskhandlarn** [comment]
It seems like you're just passing info directly from virustotal.com. Why doesn't this script use the virustotal.com API instead of going through wphunter.co?

For example, compare these:
- https://www.virustotal.com/sv/url/feb5db1be01a9980b4aed3c70ee79823898be24b3ca7477c4ba24f63d6e9536f/analysis/1521600699/
- https://www.wphunter.co/api/list.php?site=http://wordpress.com/

**Comment by Jakson2030** [comment]
The issue in this will be posting the API token, people might misusing it.

**Comment by fiskhandlarn** [comment]
@Jamalc0m maybe implement so that the script accepts your own API key as a parameter?
