### ISSUE TITLE
InsecureWarning

### ISSUE THREAD

**Issue by psychomad** [Jamalc0m/wphunter#7]
Hello
After launch wphunter i got a bunch of:

**>  InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)**

and no result, reading around i see is a problem related warnings and security. But im not a coder enough to understadn how to fix. I tried to downgrade to version:

**>  Downloading requests-2.5.3-py2.py3-none-any.whl (468kB)
>     100% |████████████████████████████████| 471kB 2.2MB/s
> Installing collected packages: requests
>   Found existing installation: requests 2.12.2
>     Uninstalling requests-2.12.2:
>       Successfully uninstalled requests-2.12.2
> Successfully installed requests-2.5.3**

And i got same bunch of message but some results (few), any tips?

Thanks

**Comment by Jakson2030** [comment]
@psychomad  Can you reproduce the steps you followed, if possible attach screenshot.

**Comment by psychomad** [comment]
Hi
For some reason today the problems disappear... weird, maybe last apt update/upgrade fix something but i don't know what. now all messages of lib disappear. Sorry can't help to understand what change
Thanks anyway

**Comment by Jakson2030** [comment]
Hi,

is it working fine with you ?
